# Generated by Django 2.1.2 on 2018-11-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0005_auto_20181117_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='Documents/'),
        ),
    ]
