# Generated by Django 2.1.2 on 2018-11-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0009_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='desktop/'),
        ),
    ]
