# Generated by Django 2.1.2 on 2018-11-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0012_auto_20181118_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(upload_to='Documents/'),
        ),
    ]
