# Generated by Django 2.1.2 on 2018-11-18 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Instagram', '0013_auto_20181118_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.FileField(upload_to='Documents/')),
                ('main_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
