# Generated by Django 2.1.2 on 2018-11-18 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Instagram', '0014_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('main_ownerr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_ownerr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
