# Generated by Django 2.1.2 on 2018-11-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0015_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='main_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_pic', to='Instagram.post'),
        ),
    ]
