# Generated by Django 2.1.2 on 2018-11-19 04:01

import Instagram.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0016_comments_main_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='Documents/'),
        ),
    ]
