# Generated by Django 2.1.2 on 2018-11-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0017_auto_20181119_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(upload_to='Documents/'),
        ),
    ]
