# Generated by Django 2.1.2 on 2018-11-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0018_auto_20181119_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='like',
            name='picture',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
